"""
Percentage Object

Fixed-point string representation of a percentage as a decimal between 0.0 and
1.0 (up to 10 decimal places supported)

Copyright © Shoobx, 2023
Schema is Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
OCF/tree/main/schema/types/Percentage.schema.json

Autogenerated, do not edit.
"""

from pydantic import constr
from pyocf.simplebase import SimpleBaseModel


class Percentage(SimpleBaseModel):
    """Percentage"""

    __root__: constr(regex=r"^0?(\.[0-9]{1,10})?$|^1(\.0{1,10})?$")
