VERSION_YEAR = 2023
VERSION_MONTH = int('02')
VERSION_DAY = int('23')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('22')
MAJOR_VERSION = 1
MINOR_VERSION = 1
PATCH_VERSION = 202302231022
version_date = '2023/02/23 10:22'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
