
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-20T20:28:52-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8ddb1880cfc2a6ba7ec4d4f09bd6208da818ae6c",
 "version": "v1.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
