"""
Custom Object

Sets forth inputs and conversion mechanism of a custom conversion, a conversion
type that cannot be accurately modelled with any other OCF conversion mechanism
type

Copyright © Shoobx, 2023
Schema is Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/t
ree/main/schema/types/conversion_mechanisms/CustomConversionMechanism.schema.jso
n

Autogenerated, do not edit.
"""

from pyocf.primitives.types.conversion_mechanisms.conversionmechanism import (
    ConversionMechanism,
)
from typing import Literal


class CustomConversionMechanism(ConversionMechanism):
    """Custom"""

    type: Literal["CUSTOM_CONVERSION"] = "CUSTOM_CONVERSION"
    # Detailed description of how the number of resulting shares should be determined?
    # Use legal language from an instrument where possible
    custom_conversion_description: str
