"""
MD5 Hash Object

String representation of MD5 hash with basic validation for a string of 32
characters composed of letters (uppercase or lowercase) and numbers

Copyright © Shoobx, 2023
Schema is Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
OCF/tree/main/schema/types/Md5.schema.json

Autogenerated, do not edit.
"""

from pydantic import constr
from pyocf.simplebase import SimpleBaseModel


class Md5(SimpleBaseModel):
    """MD5 Hash"""

    __root__: constr(regex=r"^[a-fA-F0-9]{32}$")
