
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-22T17:19:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c082d079fab0a185d05fd583a22aa56e5af7618a",
 "version": "0.0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
