"""
Day Count Type Enum

Enumeration of how the number of days are determined per period

Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
OCF/tree/main/schema/enums/DayCountType.schema.json

Autogenerated, do not edit.
"""

from enum import Enum


class DayCountType(Enum):
    ENUM_ACTUAL_365 = "ACTUAL_365"
    ENUM_30_360 = "30_360"
