"""
Security Conversion Transaction Object

Abstract object describing fields common to all conversion transaction objects

Copyright © Shoobx, 2023
Schema is Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/t
ree/main/schema/primitives/objects/transactions/conversion/Conversion.schema.jso
n

Autogenerated, do not edit.
"""

from pydantic import BaseModel


class Conversion(BaseModel):
    """Security Conversion Transaction"""

    # Identifier for the security (or securities) that resulted from the conversion
    resulting_security_ids: list[str]
