
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-12T15:26:33-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3122f6e6c229c7f148887adc57b8e2c9440dae77",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
