"""
Object Object

Abstract object to be extended by all other objects

Copyright © Shoobx, 2023
Schema is Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
OCF/tree/main/schema/primitives/objects/Object.schema.json

Autogenerated, do not edit.
"""

from pydantic import BaseModel
from pyocf.enums.objecttype import ObjectType
from typing import Optional


class Object(BaseModel):
    """Object"""

    # Identifier for the object
    id: str
    # Unstructured text comments related to and stored for the object
    comments: Optional[list[str]]
    # Object type field
    object_type: ObjectType
