
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-20T11:45:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c1b5915d1b199d8a2920a379756e52a892fd3fd1",
 "version": "1.18.2.post0.dev127"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
