"""
    Hwmux reservations MV API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import resview_client
from resview_client.api.reservations_api import ReservationsApi  # noqa: E501


class TestReservationsApi(unittest.TestCase):
    """ReservationsApi unit test stubs"""

    def setUp(self):
        self.api = ReservationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_reservation_get_batch_api_reservations_get_batch_post(self):
        """Test case for reservation_get_batch_api_reservations_get_batch_post

        Reservation Get Batch  # noqa: E501
        """
        pass

    def test_reservations_detail_api_reservations_id_get(self):
        """Test case for reservations_detail_api_reservations_id_get

        Reservations Detail  # noqa: E501
        """
        pass

    def test_reservations_list_api_reservations_get(self):
        """Test case for reservations_list_api_reservations_get

        Reservations List  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
