"""
    Hwmux reservations MV API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import resview_client
from resview_client.model.reservation_batch_get_request import ReservationBatchGetRequest


class TestReservationBatchGetRequest(unittest.TestCase):
    """ReservationBatchGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReservationBatchGetRequest(self):
        """Test ReservationBatchGetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReservationBatchGetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
