
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-23T21:55:39+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b31887ce048742ac5d4bf678a7e974c38ed01fc8",
 "version": "1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
