
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-23T16:31:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "07de1ac43adb2360f5b6c58396f4b645ddc50b5f",
 "version": "2.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
