
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-22T10:23:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e122312d87e155e56afba81b81b0b880b545f99f",
 "version": "0.2.0.post0.dev123"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
