# Generated by Django 4.1.7 on 2023-02-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0002_procedure_executed_alter_procedure_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='logs',
            field=models.TextField(default=str),
        ),
    ]
