# Generated by Django 4.1.7 on 2023-02-21 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0004_alter_procedure_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='c_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='procedure',
            name='exception',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procedure',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='procedure.procedure'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
