
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-20T10:11:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d8777b95c7ac512010a1212f9fa5e6af99e69a69",
 "version": "1.18.2.post0.dev122"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
