
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-23T15:23:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "38d2ed95d54d285b6bff1c42656005998186daa6",
 "version": "2023.02.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
