VERSION_YEAR = 2023
VERSION_MONTH = int('02')
VERSION_DAY = int('23')
VERSION_HOUR = int('21')
VERSION_MINUTE = int('01')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202302232101
version_date = '2023/02/23 21:01'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
