# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '1.0.4'
git_version = '08dc6b1dac272bb9eec222a8125f9dc69e057dd4'
