VERSION_YEAR = 2023
VERSION_MONTH = int('02')
VERSION_DAY = int('22')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('28')
MAJOR_VERSION = 2
MINOR_VERSION = 21
PATCH_VERSION = 202302221128
version_date = '2023/02/22 11:28'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
