# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'moveFileUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MoveFile(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 654)
        self.Title = QtWidgets.QLabel(Form)
        self.Title.setGeometry(QtCore.QRect(188, 20, 431, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.filePath = QtWidgets.QLabel(Form)
        self.filePath.setGeometry(QtCore.QRect(110, 90, 91, 20))
        self.filePath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.filePath.setObjectName("filePath")
        self.FilePathEdit = QtWidgets.QLineEdit(Form)
        self.FilePathEdit.setGeometry(QtCore.QRect(240, 90, 461, 20))
        self.FilePathEdit.setMouseTracking(False)
        self.FilePathEdit.setObjectName("FilePathEdit")
        self.FilesBtn = QtWidgets.QPushButton(Form)
        self.FilesBtn.setGeometry(QtCore.QRect(750, 90, 31, 20))
        self.FilesBtn.setObjectName("btn1")
        self.DirsBtn = QtWidgets.QPushButton(Form)
        self.DirsBtn.setGeometry(QtCore.QRect(750, 150, 31, 20))
        self.DirsBtn.setObjectName("btn1")
        self.DirsPathEdit = QtWidgets.QLineEdit(Form)
        self.DirsPathEdit.setGeometry(QtCore.QRect(240, 150, 471, 20))
        self.DirsPathEdit.setMouseTracking(False)
        self.DirsPathEdit.setObjectName("DirsPathEdit")
        self.DirPath = QtWidgets.QLabel(Form)
        self.DirPath.setGeometry(QtCore.QRect(110, 150, 111, 20))
        self.DirPath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.DirPath.setObjectName("DirPath")
        self.StartBtn = QtWidgets.QPushButton(Form)
        self.StartBtn.setGeometry(QtCore.QRect(290, 210, 271, 31))
        self.StartBtn.setObjectName("btn2")
        self.textEdit = QtWidgets.QPlainTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(140, 340, 581, 131))
        self.textEdit.setObjectName("textEdit")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(140, 280, 581, 23))
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setStyleSheet("QProgressBar { border: 2px solid grey; border-radius: 5px; background-color: #FFFFFF; text-align: center;}QProgressBar::chunk {background:QLinearGradient(x1:0,y1:0,x2:2,y2:0,stop:0 #666699,stop:1  #DB7093); }")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.filePathTip = QtWidgets.QLabel(Form)
        self.filePathTip.setGeometry(QtCore.QRect(240, 120, 411, 16))
        self.filePathTip.setAlignment(QtCore.Qt.AlignCenter)
        self.filePathTip.setObjectName("filePathTip")
        self.DirPathTip = QtWidgets.QLabel(Form)
        self.DirPathTip.setGeometry(QtCore.QRect(240, 180, 411, 16))
        self.DirPathTip.setAlignment(QtCore.Qt.AlignCenter)
        self.DirPathTip.setObjectName("DirPathTip")
        self.BarText = QtWidgets.QLabel(Form)
        self.BarText.setGeometry(QtCore.QRect(420, 250, 100, 16))
        self.progressBar.raise_()
        self.BarText.raise_()
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Title.setText(_translate("Form", "复制文件到层级文件夹"))
        self.filePath.setText(_translate("Form", "文件所在位置："))
        self.FilesBtn.setText(_translate("Form", "..."))
        self.DirsBtn.setText(_translate("Form", "..."))
        self.DirPath.setText(_translate("Form", "层级文件夹位置："))
        self.StartBtn.setText(_translate("Form", "移动文件"))
        self.filePathTip.setText(_translate("Form", "提示文件所在位置的tip"))
        self.filePathTip.setStyleSheet("border-width: 0px;border-color: rgb(0, 0, 0);color:rgb(255, 0, 0)")
        self.DirPathTip.setStyleSheet("border-width: 0px;border-color: rgb(0, 0, 0);color:rgb(255, 0, 0)")
        self.filePathTip.setVisible(False)
        self.DirPathTip.setVisible(False)
        self.DirPathTip.setText(_translate("Form", "提示文件所在位置的tip"))
        self.BarText.setText(_translate("Form", "执行完毕"))
        self.BarText.setVisible(False)
        self.BarText.setStyleSheet("border-width: 0px;border-color: rgb(0, 0, 0);color:rgb(0, 0, 0); background-color: rgba(250, 0, 0,0);")