try:
    from ._crustpy import (bool_,
                           f32,
                           f64,
                           i128,
                           i16,
                           i32,
                           i64,
                           i8,
                           isize,
                           u128,
                           u16,
                           u32,
                           u64,
                           u8,
                           usize)
except ImportError:
    from ._rustpy.primitive import (bool_,
                                    f32,
                                    f64,
                                    i128,
                                    i16,
                                    i32,
                                    i64,
                                    i8,
                                    isize,
                                    u128,
                                    u16,
                                    u32,
                                    u64,
                                    u8,
                                    usize)
