
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-16T21:32:35-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "2fc0ee3567acc1720803a44ac8376657da387f08",
 "version": "0.0.7.dev20230220"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
