from ._clean_text import clean_text
from ._extract_hashtags_and_remove_hashtags import extract_hashtags_and_remove_hashtags
from ._fix_fonts import fix_fonts
from ._remove_stopwords import remove_stopwords
from ._replace_hashtags import replace_hashtags
from ._replace_url import replace_url
from ._replace_mentions import replace_mentions
from ._replace_phonenumber import replace_phoneno
from ._detect_lang import detect_language