# coding: utf-8

"""
    Hwmux reservations MV API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from resview_client.paths.api_reservationsget_batch_.post import ReservationGetBatchApiReservationsGetBatchPost
from resview_client.paths.api_reservations_id_.get import ReservationsDetailApiReservationsIdGet
from resview_client.paths.api_reservations_.get import ReservationsListApiReservationsGet


class ReservationsApi(
    ReservationGetBatchApiReservationsGetBatchPost,
    ReservationsDetailApiReservationsIdGet,
    ReservationsListApiReservationsGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
