# coding: utf-8

"""
    Tator REST API

    Interface to the Tator backend.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from tator_openapi import schemas  # noqa: F401


class AlgorithmLaunchSpec(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "algorithm_name",
        }
        
        class properties:
            algorithm_name = schemas.StrSchema
            
            
            class extra_params(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['AlgorithmParameter']:
                        return AlgorithmParameter
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['AlgorithmParameter'], typing.List['AlgorithmParameter']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'extra_params':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AlgorithmParameter':
                    return super().__getitem__(i)
            
            
            class media_ids(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.IntSchema
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, decimal.Decimal, int, ]], typing.List[typing.Union[MetaOapg.items, decimal.Decimal, int, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'media_ids':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            media_query = schemas.StrSchema
            __annotations__ = {
                "algorithm_name": algorithm_name,
                "extra_params": extra_params,
                "media_ids": media_ids,
                "media_query": media_query,
            }
    
    algorithm_name: MetaOapg.properties.algorithm_name
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["algorithm_name"]) -> MetaOapg.properties.algorithm_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["extra_params"]) -> MetaOapg.properties.extra_params: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["media_ids"]) -> MetaOapg.properties.media_ids: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["media_query"]) -> MetaOapg.properties.media_query: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["algorithm_name", "extra_params", "media_ids", "media_query", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["algorithm_name"]) -> MetaOapg.properties.algorithm_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["extra_params"]) -> typing.Union[MetaOapg.properties.extra_params, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["media_ids"]) -> typing.Union[MetaOapg.properties.media_ids, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["media_query"]) -> typing.Union[MetaOapg.properties.media_query, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["algorithm_name", "extra_params", "media_ids", "media_query", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        algorithm_name: typing.Union[MetaOapg.properties.algorithm_name, str, ],
        extra_params: typing.Union[MetaOapg.properties.extra_params, list, tuple, schemas.Unset] = schemas.unset,
        media_ids: typing.Union[MetaOapg.properties.media_ids, list, tuple, schemas.Unset] = schemas.unset,
        media_query: typing.Union[MetaOapg.properties.media_query, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AlgorithmLaunchSpec':
        return super().__new__(
            cls,
            *args,
            algorithm_name=algorithm_name,
            extra_params=extra_params,
            media_ids=media_ids,
            media_query=media_query,
            _configuration=_configuration,
            **kwargs,
        )

from tator_openapi.model.algorithm_parameter import AlgorithmParameter
