# coding: utf-8

"""
    Tator REST API

    Interface to the Tator backend.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from tator_openapi import schemas  # noqa: F401


class LocalizationType(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Localization type.
    """


    class MetaOapg:
        
        class properties:
            
            
            class attribute_types(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['AttributeType']:
                        return AttributeType
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['AttributeType'], typing.List['AttributeType']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'attribute_types':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AttributeType':
                    return super().__getitem__(i)
        
            @staticmethod
            def colorMap() -> typing.Type['ColorMap']:
                return ColorMap
            description = schemas.StrSchema
            drawable = schemas.BoolSchema
            
            
            class dtype(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "box": "BOX",
                        "line": "LINE",
                        "dot": "DOT",
                        "poly": "POLY",
                    }
                
                @schemas.classproperty
                def BOX(cls):
                    return cls("box")
                
                @schemas.classproperty
                def LINE(cls):
                    return cls("line")
                
                @schemas.classproperty
                def DOT(cls):
                    return cls("dot")
                
                @schemas.classproperty
                def POLY(cls):
                    return cls("poly")
            grouping_default = schemas.BoolSchema
            id = schemas.IntSchema
            
            
            class line_width(
                schemas.IntSchema
            ):
            
            
                class MetaOapg:
                    inclusive_minimum = 1
            
            
            class media(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    
                    class items(
                        schemas.IntSchema
                    ):
                    
                    
                        class MetaOapg:
                            inclusive_minimum = 1
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, decimal.Decimal, int, ]], typing.List[typing.Union[MetaOapg.items, decimal.Decimal, int, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'media':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            name = schemas.StrSchema
            project = schemas.IntSchema
            visible = schemas.BoolSchema
            __annotations__ = {
                "attribute_types": attribute_types,
                "colorMap": colorMap,
                "description": description,
                "drawable": drawable,
                "dtype": dtype,
                "grouping_default": grouping_default,
                "id": id,
                "line_width": line_width,
                "media": media,
                "name": name,
                "project": project,
                "visible": visible,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["attribute_types"]) -> MetaOapg.properties.attribute_types: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["colorMap"]) -> 'ColorMap': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["drawable"]) -> MetaOapg.properties.drawable: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dtype"]) -> MetaOapg.properties.dtype: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["grouping_default"]) -> MetaOapg.properties.grouping_default: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["line_width"]) -> MetaOapg.properties.line_width: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["media"]) -> MetaOapg.properties.media: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["project"]) -> MetaOapg.properties.project: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["visible"]) -> MetaOapg.properties.visible: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["attribute_types", "colorMap", "description", "drawable", "dtype", "grouping_default", "id", "line_width", "media", "name", "project", "visible", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["attribute_types"]) -> typing.Union[MetaOapg.properties.attribute_types, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["colorMap"]) -> typing.Union['ColorMap', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["drawable"]) -> typing.Union[MetaOapg.properties.drawable, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dtype"]) -> typing.Union[MetaOapg.properties.dtype, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["grouping_default"]) -> typing.Union[MetaOapg.properties.grouping_default, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["line_width"]) -> typing.Union[MetaOapg.properties.line_width, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["media"]) -> typing.Union[MetaOapg.properties.media, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["project"]) -> typing.Union[MetaOapg.properties.project, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["visible"]) -> typing.Union[MetaOapg.properties.visible, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["attribute_types", "colorMap", "description", "drawable", "dtype", "grouping_default", "id", "line_width", "media", "name", "project", "visible", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        attribute_types: typing.Union[MetaOapg.properties.attribute_types, list, tuple, schemas.Unset] = schemas.unset,
        colorMap: typing.Union['ColorMap', schemas.Unset] = schemas.unset,
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        drawable: typing.Union[MetaOapg.properties.drawable, bool, schemas.Unset] = schemas.unset,
        dtype: typing.Union[MetaOapg.properties.dtype, str, schemas.Unset] = schemas.unset,
        grouping_default: typing.Union[MetaOapg.properties.grouping_default, bool, schemas.Unset] = schemas.unset,
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        line_width: typing.Union[MetaOapg.properties.line_width, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        media: typing.Union[MetaOapg.properties.media, list, tuple, schemas.Unset] = schemas.unset,
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        project: typing.Union[MetaOapg.properties.project, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        visible: typing.Union[MetaOapg.properties.visible, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'LocalizationType':
        return super().__new__(
            cls,
            *args,
            attribute_types=attribute_types,
            colorMap=colorMap,
            description=description,
            drawable=drawable,
            dtype=dtype,
            grouping_default=grouping_default,
            id=id,
            line_width=line_width,
            media=media,
            name=name,
            project=project,
            visible=visible,
            _configuration=_configuration,
            **kwargs,
        )

from tator_openapi.model.attribute_type import AttributeType
from tator_openapi.model.color_map import ColorMap
