# coding: utf-8

"""
    Tator REST API

    Interface to the Tator backend.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from tator_openapi import schemas  # noqa: F401


class MediaUpdate(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            
            
            class archive_state(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "to_archive": "ARCHIVE",
                        "to_live": "LIVE",
                    }
                
                @schemas.classproperty
                def ARCHIVE(cls):
                    return cls("to_archive")
                
                @schemas.classproperty
                def LIVE(cls):
                    return cls("to_live")
            
            
            class attributes(
                schemas.DictSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def additional_properties() -> typing.Type['AttributeValue']:
                        return AttributeValue
                
                def __getitem__(self, name: typing.Union[str, ]) -> 'AttributeValue':
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> 'AttributeValue':
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *args: typing.Union[dict, frozendict.frozendict, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: 'AttributeValue',
                ) -> 'attributes':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            codec = schemas.StrSchema
            
            
            class concat(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ConcatDefinition']:
                        return ConcatDefinition
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ConcatDefinition'], typing.List['ConcatDefinition']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'concat':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ConcatDefinition':
                    return super().__getitem__(i)
            fps = schemas.NumberSchema
            height = schemas.IntSchema
            last_edit_end = schemas.DateTimeSchema
            last_edit_start = schemas.DateTimeSchema
        
            @staticmethod
            def live() -> typing.Type['LiveUpdateDefinition']:
                return LiveUpdateDefinition
        
            @staticmethod
            def media_files() -> typing.Type['MediaFiles']:
                return MediaFiles
        
            @staticmethod
            def multi() -> typing.Type['MultiDefinition']:
                return MultiDefinition
            name = schemas.StrSchema
            
            
            class num_frames(
                schemas.IntSchema
            ):
            
            
                class MetaOapg:
                    inclusive_minimum = 0
            summaryLevel = schemas.IntSchema
            width = schemas.IntSchema
            __annotations__ = {
                "archive_state": archive_state,
                "attributes": attributes,
                "codec": codec,
                "concat": concat,
                "fps": fps,
                "height": height,
                "last_edit_end": last_edit_end,
                "last_edit_start": last_edit_start,
                "live": live,
                "media_files": media_files,
                "multi": multi,
                "name": name,
                "num_frames": num_frames,
                "summaryLevel": summaryLevel,
                "width": width,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["archive_state"]) -> MetaOapg.properties.archive_state: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["attributes"]) -> MetaOapg.properties.attributes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["codec"]) -> MetaOapg.properties.codec: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["concat"]) -> MetaOapg.properties.concat: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fps"]) -> MetaOapg.properties.fps: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["height"]) -> MetaOapg.properties.height: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["last_edit_end"]) -> MetaOapg.properties.last_edit_end: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["last_edit_start"]) -> MetaOapg.properties.last_edit_start: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["live"]) -> 'LiveUpdateDefinition': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["media_files"]) -> 'MediaFiles': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["multi"]) -> 'MultiDefinition': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["num_frames"]) -> MetaOapg.properties.num_frames: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["summaryLevel"]) -> MetaOapg.properties.summaryLevel: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["width"]) -> MetaOapg.properties.width: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["archive_state", "attributes", "codec", "concat", "fps", "height", "last_edit_end", "last_edit_start", "live", "media_files", "multi", "name", "num_frames", "summaryLevel", "width", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["archive_state"]) -> typing.Union[MetaOapg.properties.archive_state, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["attributes"]) -> typing.Union[MetaOapg.properties.attributes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["codec"]) -> typing.Union[MetaOapg.properties.codec, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["concat"]) -> typing.Union[MetaOapg.properties.concat, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fps"]) -> typing.Union[MetaOapg.properties.fps, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["height"]) -> typing.Union[MetaOapg.properties.height, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["last_edit_end"]) -> typing.Union[MetaOapg.properties.last_edit_end, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["last_edit_start"]) -> typing.Union[MetaOapg.properties.last_edit_start, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["live"]) -> typing.Union['LiveUpdateDefinition', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["media_files"]) -> typing.Union['MediaFiles', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["multi"]) -> typing.Union['MultiDefinition', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["num_frames"]) -> typing.Union[MetaOapg.properties.num_frames, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["summaryLevel"]) -> typing.Union[MetaOapg.properties.summaryLevel, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["width"]) -> typing.Union[MetaOapg.properties.width, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["archive_state", "attributes", "codec", "concat", "fps", "height", "last_edit_end", "last_edit_start", "live", "media_files", "multi", "name", "num_frames", "summaryLevel", "width", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        archive_state: typing.Union[MetaOapg.properties.archive_state, str, schemas.Unset] = schemas.unset,
        attributes: typing.Union[MetaOapg.properties.attributes, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        codec: typing.Union[MetaOapg.properties.codec, str, schemas.Unset] = schemas.unset,
        concat: typing.Union[MetaOapg.properties.concat, list, tuple, schemas.Unset] = schemas.unset,
        fps: typing.Union[MetaOapg.properties.fps, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        height: typing.Union[MetaOapg.properties.height, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        last_edit_end: typing.Union[MetaOapg.properties.last_edit_end, str, datetime, schemas.Unset] = schemas.unset,
        last_edit_start: typing.Union[MetaOapg.properties.last_edit_start, str, datetime, schemas.Unset] = schemas.unset,
        live: typing.Union['LiveUpdateDefinition', schemas.Unset] = schemas.unset,
        media_files: typing.Union['MediaFiles', schemas.Unset] = schemas.unset,
        multi: typing.Union['MultiDefinition', schemas.Unset] = schemas.unset,
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        num_frames: typing.Union[MetaOapg.properties.num_frames, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        summaryLevel: typing.Union[MetaOapg.properties.summaryLevel, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        width: typing.Union[MetaOapg.properties.width, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MediaUpdate':
        return super().__new__(
            cls,
            *args,
            archive_state=archive_state,
            attributes=attributes,
            codec=codec,
            concat=concat,
            fps=fps,
            height=height,
            last_edit_end=last_edit_end,
            last_edit_start=last_edit_start,
            live=live,
            media_files=media_files,
            multi=multi,
            name=name,
            num_frames=num_frames,
            summaryLevel=summaryLevel,
            width=width,
            _configuration=_configuration,
            **kwargs,
        )

from tator_openapi.model.attribute_value import AttributeValue
from tator_openapi.model.concat_definition import ConcatDefinition
from tator_openapi.model.live_update_definition import LiveUpdateDefinition
from tator_openapi.model.media_files import MediaFiles
from tator_openapi.model.multi_definition import MultiDefinition
