# coding: utf-8

"""
    Tator REST API

    Interface to the Tator backend.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from tator_openapi import schemas  # noqa: F401


class UploadPart(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            ETag = schemas.StrSchema
            PartNumber = schemas.IntSchema
            __annotations__ = {
                "ETag": ETag,
                "PartNumber": PartNumber,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ETag"]) -> MetaOapg.properties.ETag: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PartNumber"]) -> MetaOapg.properties.PartNumber: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["ETag", "PartNumber", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ETag"]) -> typing.Union[MetaOapg.properties.ETag, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PartNumber"]) -> typing.Union[MetaOapg.properties.PartNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["ETag", "PartNumber", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        ETag: typing.Union[MetaOapg.properties.ETag, str, schemas.Unset] = schemas.unset,
        PartNumber: typing.Union[MetaOapg.properties.PartNumber, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UploadPart':
        return super().__new__(
            cls,
            *args,
            ETag=ETag,
            PartNumber=PartNumber,
            _configuration=_configuration,
            **kwargs,
        )
