# !/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# Copyright (c) 2023 Baidu.com, Inc. All Rights Reserved

WORKSPACE_ID = "WORKSPACE_ID"
MODEL_STORE_NAME = "MODEL_STORE_NAME"
MODEL_NAME = "MODEL_NAME"
MODEL_VERSION = "MODEL_VERSION"

TIME_DIRECTORY_FORMAT = '%Y-%m-%d/%H'

CAPTURE_DATA_DIR = 'CAPTURE_DATA_DIR'

ENABLE_CAPTURE_INPUT = 'ENABLE_CAPTURE_REQUEST'
ENABLE_CAPTURE_PREDICTION = 'ENABLE_CAPTURE_RESPONSE'
ENABLE_CAPTURE_GROUND_TRUTH = 'ENABLE_CAPTURE_GROUND_TRUTH'

DEFAULT_CAPTURE_DATA_PATH = '/home/model_data_capture'
DEFAULT_CAPTURE_LOG_FILE_PATH = 'predictions/result.jsonl'
DEFAULT_CAPTURE_IMAGE_DIR_PATH = 'images'
DEFAULT_CAPTURE_BLOB_DIR_PATH = 'blobs'
