
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-23T20:31:31-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e334da413eedb083da6d889469c28ff9c39e1582",
 "version": "v0.0.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
