
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-22T15:54:23-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "da1e9446a107ffa2fc9de633c4553e74cd23ec32",
 "version": "2023.2.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
