
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-20T14:46:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "28d94fdaa7a3ddb83b0b854ae00fc7f2c3e1510f",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
