
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-20T06:01:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5cc9281c0a3e09013231643b938f8ed0bd208b8f",
 "version": "1.18.2.post0.dev115"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
