"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces  # noqa: E501

    The version of the OpenAPI document: 4.46.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.audit_log_event import AuditLogEvent
globals()['AuditLogEvent'] = AuditLogEvent
from kdp_api.model.audit_log_message import AuditLogMessage


class TestAuditLogMessage(unittest.TestCase):
    """AuditLogMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuditLogMessage(self):
        """Test AuditLogMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuditLogMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
