from enum import Enum


class AccountCustomerTrustRequestTrustNature(str, Enum):
    BARE_TRUSTS = "BARE_TRUSTS"
    INTEREST_IN_POSSESSION_TRUSTS = "INTEREST_IN_POSSESSION_TRUSTS"
    DISCRETIONARY_TRUSTS = "DISCRETIONARY_TRUSTS"
    ACCUMULATION_TRUSTS = "ACCUMULATION_TRUSTS"
    MIXED_TRUSTS = "MIXED_TRUSTS"
    SETTLOR_INTERESTED_TRUSTS = "SETTLOR_INTERESTED_TRUSTS"
    NON_RESIDENT_TRUSTS = "NON_RESIDENT_TRUSTS"
    OFFSHORE_TRUSTS = "OFFSHORE_TRUSTS"
    FAMILY_LIVING_TRUST = "FAMILY_LIVING_TRUST"
    PILOT_TRUST = "PILOT_TRUST"
    VULNERABLE_BENEFICIARY_TRUST = "VULNERABLE_BENEFICIARY_TRUST"
    CHARITABLE_TRUSTS = "CHARITABLE_TRUSTS"
    IRREVOCABLE_LIFE_INSURANCE_TRUST = "IRREVOCABLE_LIFE_INSURANCE_TRUST"
    TESTAMENTARY_TRUSTS = "TESTAMENTARY_TRUSTS"
    OTHER = "OTHER"

    def __str__(self) -> str:
        return str(self.value)
