from enum import Enum


class DirectdebitoutboundMandateCancelRequestCancellationCode(str, Enum):
    REFER_TO_PAYER = "REFER_TO_PAYER"
    INSTRUCTION_CANCELLED_BY_PAYER = "INSTRUCTION_CANCELLED_BY_PAYER"
    PAYER_DECEASED = "PAYER_DECEASED"
    ACCOUNT_TRANSFERRED = "ACCOUNT_TRANSFERRED"
    ACCOUNT_CLOSED = "ACCOUNT_CLOSED"
    ACCOUNT_OR_INSTRUCTION_TRANSFERRED = "ACCOUNT_OR_INSTRUCTION_TRANSFERRED"
    ADVANCE_NOTICE_DISPUTED = "ADVANCE_NOTICE_DISPUTED"
    INSTRUCTION_AMENDED = "INSTRUCTION_AMENDED"
    INSTRUCTION_REINSTATED = "INSTRUCTION_REINSTATED"

    def __str__(self) -> str:
        return str(self.value)
