# coding: utf-8

"""
    Hwmux reservations MV API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import resview_client
from resview_client.model.validation_error import ValidationError
from resview_client import configuration


class TestValidationError(unittest.TestCase):
    """ValidationError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
