VERSION_YEAR = 2023
VERSION_MONTH = int('02')
VERSION_DAY = int('22')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('16')
MAJOR_VERSION = 1
MINOR_VERSION = 1
PATCH_VERSION = 202302221116
version_date = '2023/02/22 11:16'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
