"""
Django settings for yangsuite project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

from yangsuite.settings.base import *     # noqa


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (os.environ.get('DJANGO_SECRET_KEY') or
              prefs.get('secret_key') or    # noqa
              # hard-coded key, only for test and debugging
              '05_)-+2+*hm6=%39!qom7l!$!f6d1jws6lp_5q8n=%nmm7*lux')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if 'DJANGO_ALLOWED_HOSTS' in os.environ:
    ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS').split()
else:
    ALLOWED_HOSTS = prefs.get('allowed_hosts', '').split()    # noqa

# In development, don't use a real e-mail server, log 'e-mails' to the console
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'mail.cisco.com'
EMAIL_PORT = 25

# Calls are made to internal Cisco github to look for updates to plugins.
# Developers can override this with environment setting.
# Customer release will override this in production.py.
GITHUB_TOKEN = os.environ.get(
    'GITHUB_TOKEN',
    "1e629a1a6c0969e5cc89ec605d9bb545e33179a7"
)
GITHUB_BASE_URL = os.environ.get(
    'GITHUB_BASE_URL',
    "https://wwwin-github.cisco.com/api/v3"
)
GITHUB_ORG = os.environ.get(
    'GITHUB_ORG',
    'yang-suite'
)
