"""
Security Acceptance Transaction Object

Abstract object describing a security acceptance transaction

Copyright © Shoobx, 2023
Schema is Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/t
ree/main/schema/primitives/objects/transactions/acceptance/Acceptance.schema.jso
n

Autogenerated, do not edit.
"""

from pydantic import BaseModel


class Acceptance(BaseModel):
    """Security Acceptance Transaction"""
