"""
Email Type Enum

Enumeration of email types

Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
OCF/tree/main/schema/enums/EmailType.schema.json

Autogenerated, do not edit.
"""

from enum import Enum


class EmailType(Enum):
    ENUM_PERSONAL = "PERSONAL"
    ENUM_BUSINESS = "BUSINESS"
    ENUM_OTHER = "OTHER"
