from politicsnlp.confucianism import *
from politicsnlp.democracy import *
from politicsnlp.freedom import *
from politicsnlp.government import *
from politicsnlp.individual import *
from politicsnlp.limited_power import *
from politicsnlp.justice import *
from politicsnlp.idealstate import *
from politicsnlp.monarch import *
from politicsnlp.people_democracy import *
from politicsnlp.person import *
from politicsnlp.protection import *
from politicsnlp.social_contract import *
from politicsnlp.spirit_of_the_law import *
