"""
Stock Classes Object

JSON containing file type identifier and list of stock classes

Copyright © Shoobx, 2023
Schema is Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
OCF/tree/main/schema/files/StockClassesFile.schema.json

Autogenerated, do not edit.
"""

from pyocf.objects.stockclass import StockClass
from pyocf.primitives.files.file import FileObject
from typing import Literal


class StockClassesFile(FileObject):
    """Stock Classes"""

    # List of OCF stock class objects
    items: list[StockClass]
    file_type: Literal["OCF_STOCK_CLASSES_FILE"] = "OCF_STOCK_CLASSES_FILE"
