"""
Vesting Terms Object

JSON containing file type identifier and list of vesting terms

Copyright © Shoobx, 2023
Schema is Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
OCF/tree/main/schema/files/VestingTermsFile.schema.json

Autogenerated, do not edit.
"""

from pyocf.objects.vestingterms import VestingTerms
from pyocf.primitives.files.file import FileObject
from typing import Literal


class VestingTermsFile(FileObject):
    """Vesting Terms"""

    # List of OCF vesting terms objects
    items: list[VestingTerms]
    file_type: Literal["OCF_VESTING_TERMS_FILE"] = "OCF_VESTING_TERMS_FILE"
