# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deepomatic/oef/protos/models/image/segmentation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from deepomatic.oef.protos.models.image import backbones_pb2 as deepomatic_dot_oef_dot_protos_dot_models_dot_image_dot_backbones__pb2
from deepomatic.oef.protos.models.image import detection_pb2 as deepomatic_dot_oef_dot_protos_dot_models_dot_image_dot_detection__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='deepomatic/oef/protos/models/image/segmentation.proto',
  package='deepomatic.oef.models.image.segmentation',
  syntax='proto2',
  serialized_pb=_b('\n5deepomatic/oef/protos/models/image/segmentation.proto\x12(deepomatic.oef.models.image.segmentation\x1a\x32\x64\x65\x65pomatic/oef/protos/models/image/backbones.proto\x1a\x32\x64\x65\x65pomatic/oef/protos/models/image/detection.proto\"\xb5\x01\n\x18MaskRCNNMetaArchitecture\x12I\n\nparameters\x18\x01 \x02(\x0b\x32\x35.deepomatic.oef.models.image.detection.RCNNParameters\x12\x19\n\x11initial_crop_size\x18\x02 \x02(\x05\x12\x1b\n\x13maxpool_kernel_size\x18\x03 \x02(\x05\x12\x16\n\x0emaxpool_stride\x18\x04 \x02(\x05\"\xe0\x01\n\x0cSegmentation\x12\x41\n\x08\x62\x61\x63kbone\x18\x01 \x02(\x0b\x32/.deepomatic.oef.models.image.backbones.Backbone\x12\x1a\n\x0flabel_smoothing\x18\x02 \x01(\x02:\x01\x30\x12W\n\tmask_rcnn\x18\x03 \x01(\x0b\x32\x42.deepomatic.oef.models.image.segmentation.MaskRCNNMetaArchitectureH\x00\x42\x18\n\x16meta_architecture_type')
  ,
  dependencies=[deepomatic_dot_oef_dot_protos_dot_models_dot_image_dot_backbones__pb2.DESCRIPTOR,deepomatic_dot_oef_dot_protos_dot_models_dot_image_dot_detection__pb2.DESCRIPTOR,])




_MASKRCNNMETAARCHITECTURE = _descriptor.Descriptor(
  name='MaskRCNNMetaArchitecture',
  full_name='deepomatic.oef.models.image.segmentation.MaskRCNNMetaArchitecture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameters', full_name='deepomatic.oef.models.image.segmentation.MaskRCNNMetaArchitecture.parameters', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initial_crop_size', full_name='deepomatic.oef.models.image.segmentation.MaskRCNNMetaArchitecture.initial_crop_size', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxpool_kernel_size', full_name='deepomatic.oef.models.image.segmentation.MaskRCNNMetaArchitecture.maxpool_kernel_size', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxpool_stride', full_name='deepomatic.oef.models.image.segmentation.MaskRCNNMetaArchitecture.maxpool_stride', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=385,
)


_SEGMENTATION = _descriptor.Descriptor(
  name='Segmentation',
  full_name='deepomatic.oef.models.image.segmentation.Segmentation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='backbone', full_name='deepomatic.oef.models.image.segmentation.Segmentation.backbone', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label_smoothing', full_name='deepomatic.oef.models.image.segmentation.Segmentation.label_smoothing', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mask_rcnn', full_name='deepomatic.oef.models.image.segmentation.Segmentation.mask_rcnn', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='meta_architecture_type', full_name='deepomatic.oef.models.image.segmentation.Segmentation.meta_architecture_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=388,
  serialized_end=612,
)

_MASKRCNNMETAARCHITECTURE.fields_by_name['parameters'].message_type = deepomatic_dot_oef_dot_protos_dot_models_dot_image_dot_detection__pb2._RCNNPARAMETERS
_SEGMENTATION.fields_by_name['backbone'].message_type = deepomatic_dot_oef_dot_protos_dot_models_dot_image_dot_backbones__pb2._BACKBONE
_SEGMENTATION.fields_by_name['mask_rcnn'].message_type = _MASKRCNNMETAARCHITECTURE
_SEGMENTATION.oneofs_by_name['meta_architecture_type'].fields.append(
  _SEGMENTATION.fields_by_name['mask_rcnn'])
_SEGMENTATION.fields_by_name['mask_rcnn'].containing_oneof = _SEGMENTATION.oneofs_by_name['meta_architecture_type']
DESCRIPTOR.message_types_by_name['MaskRCNNMetaArchitecture'] = _MASKRCNNMETAARCHITECTURE
DESCRIPTOR.message_types_by_name['Segmentation'] = _SEGMENTATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MaskRCNNMetaArchitecture = _reflection.GeneratedProtocolMessageType('MaskRCNNMetaArchitecture', (_message.Message,), dict(
  DESCRIPTOR = _MASKRCNNMETAARCHITECTURE,
  __module__ = 'deepomatic.oef.protos.models.image.segmentation_pb2'
  # @@protoc_insertion_point(class_scope:deepomatic.oef.models.image.segmentation.MaskRCNNMetaArchitecture)
  ))
_sym_db.RegisterMessage(MaskRCNNMetaArchitecture)

Segmentation = _reflection.GeneratedProtocolMessageType('Segmentation', (_message.Message,), dict(
  DESCRIPTOR = _SEGMENTATION,
  __module__ = 'deepomatic.oef.protos.models.image.segmentation_pb2'
  # @@protoc_insertion_point(class_scope:deepomatic.oef.models.image.segmentation.Segmentation)
  ))
_sym_db.RegisterMessage(Segmentation)


# @@protoc_insertion_point(module_scope)
