import os

def makeUIcodeHeader(Version, filePath, UIV, end=""):
    headerLines = [
        f"Code generated by reading UI file: {os.path.basename(filePath)}",
        f"",
        f"UI Version: {UIV}",
        f"Code Generater Version: {Version}",
        f"",
        f"WARNING! All changes made in this file will be lost when recompiling UI file!",
    ]
    headerDecoreLength = max([len(_) for _ in headerLines]) + 3
    header = "*"*headerDecoreLength + "\n" + "\n".join([
        f"** " + line + " "*(headerDecoreLength-len(line)-3)
        for line in headerLines
    ]) + "\n" + "*"*headerDecoreLength
    return f"\"\"\"\n{header}\n\"\"\"" + end



def makeCodeTemplateHeader():
    pass