from typing import List, Optional
from numpy import ndarray

def brute_force(line_points: ndarray, point_cloud: ndarray, parallel: bool = False) -> ndarray: ...

def kd_tree(line_points: ndarray, point_cloud: ndarray, parallel: bool = False) -> ndarray: ...
