# Generated by Django 4.1.3 on 2023-02-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0003_procedure_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
