
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-21T10:50:43-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "65f68bebf5a2e57d3c992a93b30f84e7639faa5f",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
