
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-16T07:26:41+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b4c1a04410a1ff21faac807d6965a611b5d7c9a",
 "version": "0.5.9.dev20230223"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
