
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-22T15:49:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef4fda5552e4936fa24affda680dd2603da572df",
 "version": "1.102"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
