# Generated by Django 3.1.7 on 2021-03-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='slug',
            field=models.SlugField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provincia',
            name='slug',
            field=models.SlugField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
