"""
Valuations Object

JSON containing file type identifier and list of valuations

Copyright © Shoobx, 2023
Schema is Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
OCF/tree/main/schema/files/ValuationsFile.schema.json

Autogenerated, do not edit.
"""

from pyocf.objects.valuation import Valuation
from pyocf.primitives.files.file import FileObject
from typing import Literal


class ValuationsFile(FileObject):
    """Valuations"""

    # List of OCF valuation objects
    items: list[Valuation]
    file_type: Literal["OCF_VALUATIONS_FILE"] = "OCF_VALUATIONS_FILE"
