
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-22T14:05:27-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "cd1166dbe9cf29a233414d35821ab0ac8428bbb6",
 "version": "0.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
